### PR TITLE
Computable, idealized polynomials over GF2. Some BV circuit implementations

### PR DESCRIPTION
**Pull request by Vtec234**

### CODE REVIEW

**Comment by joehendrix** [comment]
@Vtec234 Is this ready to merge?  Could you request me as a reviewer when you are ready?

**Comment by Vtec234** [comment]
@joehendrix it is ready, but I don't think I can request a review. Maybe there is a setting that needs to be flipped?

**Comment by Vtec234** [comment]
Now I also added the polynomial multiplication and modulus circuits. I have some proofs locally but they are sorry-full, so for now just adding the implementation.

**Comment by joehendrix** [comment]
@Vtec234 For testing, I'm running the "./scripts/test.sh" and that seems to be failing with this branch.  It runs a series of Mceliese key generation/signing/verification steps.  Are you able to run that?  I had to make a couple changes to crypto.lean (now in a branch I called `jhx/gf2poly`).

Unfortunately it isn't great for finding bugs since it just runs a whole bunch of code before failing in the signature verification, but it suggests something is different.  Maybe one can try running

**Comment by Vtec234** [comment]
@joehendrix I forgot to add the binary build target after updating Lake. I can't build mceliece on my current box because of some gcc issues, but if you try now it should hopefully work (the binary name may need adjusting in the script).

**Comment by joehendrix** [comment]
@Vtec234 I forgot I had fixed the binary build issue but didn't commit that.  This is a runtime error:

```
+ ./build/bin/crypto tmp/kat_kem.req tmp/kat_kem.rsp
uncaught exception: crypto_kem_dec failed.
```

For some reason, the math isn't working out so key decryption is failing.

**Comment by joehendrix** [comment]
I could add a Github action to build and run the code if that would be useful.  It seems like a Docker image would be useful to have if your main machine's gcc is having issues.

**Comment by Vtec234** [comment]
Yep, I need to fix my gcc or set up Docker. A CI action would be useful to have regardless.

> For some reason, the math isn't working out so key decryption is failing.

Do you mean that this is the case with this PR, or was also the case before? If it is the former, I can look into it.

**Comment by joehendrix** [comment]
Yes, it's an issue in the PR.  The main branch is currently running successfully.

**Review by joehendrix — APPROVED** [review]
I haven't closely reviewed the GF2 code, but the cleanups look good to me.

**Pull request merged**
